Rename to meepo2
huskar-org/meepo2 pull request #2
Opened 2019-09-25 07:45 UTC by 647-coder

2019-09-25 08:52 UTC, mozillazg requested changes
CI 没过

2019-09-26 02:54 UTC, mozillazg commented on meepo2/signals.py
> +_monkey_patch_hashable_func()
把这个 from 提前可能会导致 _monkey_patch_hashable_func 失效。

2019-09-26 02:58 UTC, mozillazg commented on meepo2/signals.py
> +_monkey_patch_hashable_func()
pep8 相关的问题可以直接设置 ignore 来忽略掉，不在这个 PR 解决。

可以在 tox.ini 中增加类似下面的配置来配置 flake8：

```
[flake8]
ignore = E402,Exxx
```

2019-09-26 03:00 UTC, mozillazg commented on setup.py
> +    "mysql-replication>=0.9,<0.19",
这个 PR 只是重命名，其他任何非必须的变更都不要有，不然无法保证是否破坏了原有的功能。

2019-09-26 03:01 UTC, mozillazg commented on =2.2.5
> +Requirement already satisfied: flake8 in /Users/lliusiqi/ali/meepo2-env/lib/python2.7/site-packages (3.7.8)
乱入了一些文件

2019-09-27 10:04 UTC, 647-coder commented
ready for review

2019-09-27 10:10 UTC, mozillazg commented
LGTM

2019-09-27 10:10 UTC, mozillazg approved these changes

2019-09-27 10:35 UTC, merged